import { NextPage } from "next";
import Head from "next/head";

const Index: NextPage = () => {
  return (
    <>
      <Head>
        <title>google-maps</title>
        <meta name="description" content="Generated by Create Next Stack." />
      </Head>
    </>
  );
};

export default Index;
